Azure.Architecture.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Azure.Architecture.Extractor.Services;
using static Azure.Architecture.Extractor.Services.UpdateResult;

namespace Azure.Architecture.Web.Pages;

public class IndexModel : PageModel
{
    private readonly IServiceMediator _extractorService;
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(IServiceMediator extractorService, ILogger<IndexModel> logger)
    {
        _extractorService = extractorService ?? throw new ArgumentNullException(nameof(extractorService));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    public async Task OnGet()
    {
        await PopulateServiceAndDependenciesAsync();
    }

    public async Task OnPostPopulate()
    {
        UpdateResult = await _extractorService.ExtractDataAsync();

        // TBD
        switch (UpdateResult)
        {
            case Failure failure:
                _logger.LogError(failure.Exception, "Unable to load services");
                break;
        }

        await PopulateServiceAndDependenciesAsync();
    }

    private async Task PopulateServiceAndDependenciesAsync()
    {
        var (services, dependencies) = await _extractorService.GetServiceAndDependenciesAsync();
        Services = new SelectList(services);
        Dependencies = new SelectList(dependencies);
    }

    public async Task OnPostInit()
    {
        await _extractorService.ReinitializeDbAsync();
        await PopulateServiceAndDependenciesAsync();
    }

    public async Task OnPostView()
    {
        DotGraph = await _extractorService.GenerateGraphAsync(SelectedServices, SelectedDependencies);
        await PopulateServiceAndDependenciesAsync();
    }

    public SelectList Services { get; set; } = null!;
    public SelectList Dependencies { get; set; } = null!;

    [BindProperty]
    public string[] SelectedServices { get; set; } = null!;

    [BindProperty]
    public string[] SelectedDependencies { get; set; } = null!;

    public string? DotGraph { get; private set; }

    public UpdateResult? UpdateResult { get; private set; }
}

Azure.Architecture.Web/Pages/Index.cshtml
@page
@using Azure.Architecture.Extractor.Services;
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

@section NavBar {
    <form asp-page-handler="view" id="viewForm" method="post" class="mr-auto">
        <select class="selectpicker pt-1 pb-1 navbar mr-auto"
            asp-for="SelectedServices"
            asp-items="Model.Services"
            multiple data-live-search="true"
            data-selected-text-format="count"
            title="Choose services">
        </select>
        <select class="selectpicker pt-1 pb-1 navbar mr-auto"
            asp-for="SelectedDependencies"
            asp-items="Model.Dependencies"
            multiple data-live-search="true"
            data-selected-text-format="count"
            title="Choose dependencies">
        </select>
    </form>
}

@section SideBar {
    <li class="nav-item">
        <form asp-page-handler="populate" class="form-inline" method="post">
            <button class="bg-light nav-link border-0 btn-lg btn-block no-shadow" data-toggle="modal" data-target="#populate-modal">Populate Db</button>
        </form>
    </li>
    <li class="nav-item">
        <form asp-page-handler="init" method="post">
            <button class="bg-light nav-link border-0 btn-lg btn-block no-shadow">Reinitialize Db</button>
        </form>
    </li>
}

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    <script src="~/js/svg-pan-zoom.min.js" asp-append-version="true"></script>
    <script type="text/javascript">
        $('.selectpicker').selectpicker({ actionsBox: true }).on('hidden.bs.select', function (e) {
            $('#viewForm').submit()
        });

        $(document).ready(function () {
            $('*[data-show]').modal();
        });
    </script>
    @if (!string.IsNullOrEmpty(Model.DotGraph))
    {
        <script type="text/javascript">
            const workerURL = '/js/full.render.js';
            const renderOptions = {
                engine: 'dot',
            };
            let viz = new Viz({ workerURL });
            let dotGraph = $('#dotGraph').text();

            viz.renderSVGElement(dotGraph, renderOptions)
                .then(function (element) {
                    $('#graph')[0].appendChild(element);
                    const panZoomInstance = svgPanZoom(element, {
                        zoomEnabled: true,
                        controlIconsEnabled: true,
                        fit: true,
                        center: true,
                    });
                    panZoomInstance.zoom(0.8)
                })
        </script>
    }
}

@if (!string.IsNullOrEmpty(Model.DotGraph))
{
    <div class="graph-container">
        <div class="graph" id="graph">
        </div>
        <div id="dotGraph" style="display: none">
            @Model.DotGraph
        </div>
    </div>
}

<div class="modal fade bd-example-modal-sm" id="populate-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Operation in progress</h5>
            </div>
            <div class="modal-body">
                Loading services and dependencies in progress....
            </div>
        </div>
    </div>
</div>

@if (Model.UpdateResult is not null)
{
    if (Model.UpdateResult is UpdateResult.Success success)
    {
        <div class="modal fade bd-example-modal-sm" id="populate-result-modal" role="dialog" data-show="true" aria-labelledby="mySmallModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Operation completed</h5>
                    </div>
                    <div class="modal-body">
                        Added @success.NewServices new services and @success.NewDependencies new dependencies
                    </div>
                </div>
            </div>
        </div>
    }
    else if (Model.UpdateResult is UpdateResult.Failure failure)
    {
        <div class="modal fade bd-example-modal-md" id="populate-result-failure-modal" role="dialog" data-show="true" aria-labelledby="mySmallModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-md">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Operation failed</h5>
                    </div>
                    <div class="modal-body">
                        Following error happened during execution of the operation
                        <br />
                        <em>@failure.Exception.Message</em>
                        <br />
                        Check the log for more detailed info
                    </div>
                </div>
            </div>
        </div>
    }
}

Azure.Architecture.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Rnhb Architecture</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow clearfix">
            <a class="navbar-brand col-sm-3 col-md-2 mr-0 ml-1" asp-page="/Index">Azure Architecture</a>
            @await RenderSectionAsync("NavBar", required: false)
        </nav>
    </header>

    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 col-sm-2 col-xs-2 col-lg-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-sticky">
                    <ul class="nav flex-column pr-1">
                        @await RenderSectionAsync("SideBar", required: false)
                    </ul>
                </div>
            </nav>
            <main role="main" class="col-md-10 ml-sm-auto col-lg-10 px-4 main">
                @RenderBody()
            </main>
        </div>
    </div>

@*    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Rnhb.Architecture.Web
        </div>
    </footer>*@
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="~/js/viz.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>